server:
  port: 7777

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/hardwarestore-user-db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

app:
  jwtSecret: dGhpcyBpcyBhIGtleSBmb3IgdGhhdCB3aWxsIGJlIHVzZWQgd2hlbiBkZWZpbml0ZWx5IGluIGJ1ZmZlciBpbiB0aGVpciBwcmVmZXJzZWQgSE1BQy1TSEEyNTYgaW1hZ2VzLi4u
  jwtExpireMs: 120000
  jwtRefreshExpireMs: 120000